// import './1_Fibonacci'
// import './2_Factorial'
// import './3_List'
// import './4_CezarCode'
// import './5_Bind'
// import './6_BubbleSort'
// import './7_Bogosort'
// import './8_SelectionSort'
// import './9_Tree'
// import './10_DateSort'
// import './11_Iterator'
// import './12_Closure'
// import '../css/style.sass'
// import '../js/13_SOLID'
// import './14_TypeJS.ts'
import './webSocket.js'
